-- begin LIPAFARE_VEHICLES
alter table LIPAFARE_VEHICLES add constraint FK_LIPAFARE_VEHICLES_ON_VEHICLE_OWNER foreign key (VEHICLE_OWNER_ID) references LIPAFARE_CUSTOMERS(ID)^
create unique index IDX_LIPAFARE_VEHICLES_UK_VEHICLE_CODE on LIPAFARE_VEHICLES (VEHICLE_CODE) where DELETE_TS is null ^
create unique index IDX_LIPAFARE_VEHICLES_UK_PLATE_NUMBER on LIPAFARE_VEHICLES (PLATE_NUMBER) where DELETE_TS is null ^
create index IDX_LIPAFARE_VEHICLES_ON_VEHICLE_OWNER on LIPAFARE_VEHICLES (VEHICLE_OWNER_ID)^
-- end LIPAFARE_VEHICLES
-- begin LIPAFARE_VEHICLE_PERMISSION_REGISTER
alter table LIPAFARE_VEHICLE_PERMISSION_REGISTER add constraint FK_LIPAFARE_VEHICLE_PERMISSION_REGISTER_ON_CUSTOMER foreign key (CUSTOMER_ID) references LIPAFARE_CUSTOMERS(ID)^
create index IDX_LIPAFARE_VEHICLE_PERMISSION_REGISTER_ON_CUSTOMER on LIPAFARE_VEHICLE_PERMISSION_REGISTER (CUSTOMER_ID)^
-- end LIPAFARE_VEHICLE_PERMISSION_REGISTER
