-- begin LIPAFARE_VEHICLES
alter table LIPAFARE_VEHICLES add constraint FK_LIPAFARE_VEHICLES_ON_VEHICLE_OWNER foreign key (VEHICLE_OWNER_ID) references LIPAFARE_CUSTOMERS(ID)^
create index IDX_LIPAFARE_VEHICLES_ON_VEHICLE_OWNER on LIPAFARE_VEHICLES (VEHICLE_OWNER_ID)^
-- end LIPAFARE_VEHICLES
