alter table LIPAFARE_VEHICLES add constraint FK_LIPAFARE_VEHICLES_ON_VEHICLE_OWNER foreign key (VEHICLE_OWNER_ID) references LIPAFARE_CUSTOMERS(ID);
create unique index IDX_LIPAFARE_VEHICLES_UK_VEHICLE_CODE on LIPAFARE_VEHICLES (VEHICLE_CODE) where DELETE_TS is null ;
create index IDX_LIPAFARE_VEHICLES_ON_VEHICLE_OWNER on LIPAFARE_VEHICLES (VEHICLE_OWNER_ID);
